FROM nasanccs/wrf-baselibs:latest

RUN git clone --recurse-submodule https://github.com/wrf-model/WRF.git /wrf/WRF \
  && cd /wrf/WRF \
  && git checkout release-v4.4.2 \
  && ./configure <<< $'34\1\n' \
  && ./compile -j 40 em_real

RUN git clone https://github.com/wrf-model/WPS.git /wrf/WPS \
  && cd /wrf/WPS \
  && git checkout release-v4.4 \
  && ./configure <<< $'3\n' \
  && ./compile

VOLUME /wrf
